import { Layout } from "@/components/Layout";
import { Button } from "@/components/ui/button";
import { FileText, Download, ShieldCheck, BookOpen, CheckCircle2 } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { signals } from "@/lib/course-data";
import { useRef } from "react";
// @ts-ignore
import html2pdf from "html2pdf.js";
import { motion } from "framer-motion";

export default function Downloads() {
  const fullCourseRef = useRef<HTMLDivElement>(null);

  const handleDownloadFullCourse = () => {
    const element = document.createElement('div');
    element.innerHTML = `
      <div style="font-family: sans-serif; padding: 20px;">
        <h1 style="text-align: center; font-size: 32px; margin-bottom: 20px;">Mobile Crane Hand Signals - Complete Course Handbook</h1>
        <p style="text-align: center; margin-bottom: 40px;">Educational material for standard construction crane signals.</p>
        
        ${signals.map(s => `
          <div style="page-break-after: always; margin-bottom: 40px; border-bottom: 1px solid #ccc; padding-bottom: 20px;">
            <h2 style="font-size: 24px; color: #333; text-transform: uppercase;">${s.name}</h2>
            <div style="margin: 20px 0;">
              <img src="${s.image}" style="max-width: 200px; display: block; margin: 0 auto;" />
            </div>
            <p><strong>Description:</strong> ${s.description}</p>
            <p><strong>How to Perform:</strong> ${s.explanation}</p>
            <p><strong>Detailed Guide:</strong> ${s.detailedExplanation}</p>
            
            <div style="margin-top: 20px;">
              <strong>Safety Notes:</strong>
              <ul>
                ${s.safetyNotes.map(n => `<li>${n}</li>`).join('')}
              </ul>
            </div>

             <div style="margin-top: 15px;">
              <strong>Common Mistakes:</strong>
              <ul>
                ${s.mistakes.map(m => `<li>${m}</li>`).join('')}
              </ul>
            </div>
          </div>
        `).join('')}

        <div style="text-align: center; margin-top: 50px; font-size: 12px; color: #666;">
          Generated by CraneSignal Pro. Verify all signals with official site safety regulations.
        </div>
      </div>
    `;

    const opt = {
      margin: 0.5,
      filename: 'crane-signals-complete-handbook.pdf',
      image: { type: 'png' as const, quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in' as const, format: 'letter' as const, orientation: 'portrait' as const }
    };

    html2pdf().set(opt).from(element).save();
  };

  const handleDownloadSignal = (signalId: string) => {
      const signal = signals.find(s => s.id === signalId);
      if(!signal) return;

       const element = document.createElement('div');
       element.innerHTML = `
      <div style="font-family: sans-serif; padding: 20px; border: 2px solid #333; border-radius: 10px;">
        <h1 style="text-align: center; font-size: 28px; text-transform: uppercase; margin-bottom: 10px;">${signal.name}</h1>
        <div style="text-align: center; margin-bottom: 20px;">
            <span style="background: #eee; padding: 5px 10px; border-radius: 4px; font-size: 12px;">${signal.category} Signal</span>
        </div>
        
        <div style="margin: 20px 0; text-align: center;">
             <img src="${signal.image}" style="max-width: 250px; display: block; margin: 0 auto;" />
        </div>

        <div style="background: #f9f9f9; padding: 15px; border-radius: 5px; margin-bottom: 20px;">
            <h3 style="margin-top: 0;">Instruction:</h3>
            <p>${signal.explanation}</p>
            <p>${signal.detailedExplanation}</p>
        </div>
        
        <div style="margin-bottom: 20px;">
             <strong>Safety Notes:</strong>
              <ul>
                ${signal.safetyNotes.map(n => `<li>${n}</li>`).join('')}
              </ul>
        </div>
        
         <div style="text-align: center; margin-top: 30px; font-size: 10px; color: #666;">
          CraneSignal Pro Reference Card
        </div>
      </div>
    `;
    
    const opt = {
      margin: 0.5,
      filename: `${signal.name.toLowerCase().replace(/\s+/g, '-')}-card.pdf`,
      image: { type: 'png' as const, quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in' as const, format: 'letter' as const, orientation: 'portrait' as const }
    };

    html2pdf().set(opt).from(element).save();
  }


  return (
    <Layout>
      <div className="container px-4 md:px-6 py-12">
        {/* Header Section */}
        <motion.div 
          className="text-center mb-12"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <div className="inline-flex items-center gap-2 text-primary font-semibold mb-4">
            <Download className="h-5 w-5" />
            <span className="font-oswald uppercase tracking-wide text-sm">Offline Resources</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-bold font-oswald uppercase mb-4">
            Download Course <span className="text-primary">Materials</span>
          </h1>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            Get the full course handbook and individual signal reference cards for offline use and jobsite safety meetings.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto">
          {/* Full Handbook */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
          >
            <Card className="border-2 border-primary/20 bg-gradient-to-br from-primary/5 to-secondary/5 h-full shadow-lg">
              <CardHeader>
                <div className="flex items-center gap-3 mb-2">
                  <div className="bg-gradient-to-br from-primary to-secondary p-3 rounded-xl shadow-md">
                    <ShieldCheck className="h-6 w-6 text-primary-foreground" />
                  </div>
                  <CardTitle className="font-oswald text-2xl">Complete Handbook</CardTitle>
                </div>
                <CardDescription>
                  All {signals.length} signals, safety guidelines, and quizzes in one document.
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <ul className="space-y-3 text-sm">
                  {[
                    "Printable A4 Format",
                    "High-resolution diagrams",
                    "Includes safety checklist",
                    "Complete lesson content",
                    "All quiz questions and answers"
                  ].map((item, i) => (
                    <li key={i} className="flex items-center gap-2 text-muted-foreground">
                      <CheckCircle2 className="h-4 w-4 text-primary shrink-0" />
                      {item}
                    </li>
                  ))}
                </ul>
                <Button 
                  className="w-full font-oswald uppercase bg-gradient-to-r from-primary to-secondary hover:opacity-90 transition-all duration-200 shadow-md" 
                  size="lg"
                  onClick={handleDownloadFullCourse}
                >
                  <Download className="mr-2 h-4 w-4" /> Download Full Course PDF
                </Button>
              </CardContent>
            </Card>
          </motion.div>

          {/* Individual Cards */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
          >
            <Card className="h-full shadow-lg">
              <CardHeader>
                <div className="flex items-center gap-3 mb-2">
                  <div className="bg-muted p-3 rounded-xl">
                    <FileText className="h-6 w-6 text-muted-foreground" />
                  </div>
                  <CardTitle className="font-oswald text-2xl">Signal Reference Cards</CardTitle>
                </div>
                <CardDescription>
                  Individual cards for each signal. Great for daily toolbox talks.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-3 max-h-[450px] overflow-y-auto pr-2">
                  {signals.map((s, idx) => (
                    <motion.div 
                      key={s.id} 
                      className="flex items-center justify-between p-3 rounded-xl bg-muted/30 hover:bg-muted/50 transition-colors border"
                      initial={{ opacity: 0, x: -10 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 0.3 + idx * 0.02 }}
                    >
                      <div className="flex items-center gap-3">
                        <div className="bg-primary/10 h-8 w-8 rounded-lg flex items-center justify-center text-xs font-bold text-primary">
                          {idx + 1}
                        </div>
                        <div>
                          <span className="font-medium text-sm">{s.name}</span>
                          <span className="block text-xs text-muted-foreground">{s.category}</span>
                        </div>
                      </div>
                      <Button 
                          variant="ghost" 
                          size="sm" 
                          className="h-8 text-muted-foreground hover:text-primary"
                          onClick={() => handleDownloadSignal(s.id)}
                      >
                        <Download className="h-4 w-4" />
                      </Button>
                    </motion.div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </motion.div>
        </div>

        {/* Additional Resources */}
        <motion.div 
          className="mt-16 max-w-4xl mx-auto"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
        >
          <div className="bg-card rounded-2xl border p-8 shadow-sm">
            <h3 className="text-2xl font-bold font-oswald uppercase mb-6 flex items-center gap-3">
              <BookOpen className="h-6 w-6 text-primary" />
              Additional Resources
            </h3>
            <div className="grid md:grid-cols-2 gap-6">
              {[
                {
                  title: "ANSI B30.5 Standard",
                  desc: "Official American National Standard for mobile crane hand signals.",
                  link: "#"
                },
                {
                  title: "Safety Training Videos",
                  desc: "Visual demonstrations of proper signal techniques.",
                  link: "#"
                },
                {
                  title: "Quick Reference Poster",
                  desc: "Printable poster for jobsite display.",
                  link: "#"
                },
                {
                  title: "Exam Preparation Guide",
                  desc: "Practice questions for crane operator certification.",
                  link: "#"
                }
              ].map((resource, idx) => (
                <div key={idx} className="flex items-start gap-4 p-4 rounded-xl bg-muted/30 border hover:border-primary/30 transition-colors">
                  <div className="bg-primary/10 p-2 rounded-lg mt-1">
                    <FileText className="h-4 w-4 text-primary" />
                  </div>
                  <div>
                    <h4 className="font-bold font-oswald text-sm uppercase">{resource.title}</h4>
                    <p className="text-sm text-muted-foreground mt-1">{resource.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </motion.div>
      </div>
    </Layout>
  );
}
