import { Layout } from "@/components/Layout";
import { Button } from "@/components/ui/button";
import { FileText, Download, ShieldCheck } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { signals } from "@/lib/course-data";
import { useRef } from "react";
// @ts-ignore
import html2pdf from "html2pdf.js";

export default function Downloads() {
  const fullCourseRef = useRef<HTMLDivElement>(null);

  const handleDownloadFullCourse = () => {
    // We'll create a temporary hidden element with full content for PDF generation
    // or we can generate it from the course data object
    const element = document.createElement('div');
    element.innerHTML = `
      <div style="font-family: sans-serif; padding: 20px;">
        <h1 style="text-align: center; font-size: 32px; margin-bottom: 20px;">Mobile Crane Hand Signals - Complete Course Handbook</h1>
        <p style="text-align: center; margin-bottom: 40px;">Educational material for standard construction crane signals.</p>
        
        ${signals.map(s => `
          <div style="page-break-after: always; margin-bottom: 40px; border-bottom: 1px solid #ccc; padding-bottom: 20px;">
            <h2 style="font-size: 24px; color: #333; text-transform: uppercase;">${s.name}</h2>
            <div style="margin: 20px 0;">
              <img src="${s.image}" style="max-width: 200px; display: block; margin: 0 auto;" />
            </div>
            <p><strong>Description:</strong> ${s.description}</p>
            <p><strong>How to Perform:</strong> ${s.explanation}</p>
            <p><strong>Detailed Guide:</strong> ${s.detailedExplanation}</p>
            
            <div style="margin-top: 20px;">
              <strong>Safety Notes:</strong>
              <ul>
                ${s.safetyNotes.map(n => `<li>${n}</li>`).join('')}
              </ul>
            </div>

             <div style="margin-top: 15px;">
              <strong>Common Mistakes:</strong>
              <ul>
                ${s.mistakes.map(m => `<li>${m}</li>`).join('')}
              </ul>
            </div>
          </div>
        `).join('')}

        <div style="text-align: center; margin-top: 50px; font-size: 12px; color: #666;">
          Generated by CraneSignal Pro. Verify all signals with official site safety regulations.
        </div>
      </div>
    `;

    const opt = {
      margin: 0.5,
      filename: 'crane-signals-complete-handbook.pdf',
      image: { type: 'png' as const, quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
    };

    html2pdf().set(opt).from(element).save();
  };

  const handleDownloadSignal = (signalId: string) => {
      const signal = signals.find(s => s.id === signalId);
      if(!signal) return;

       const element = document.createElement('div');
       element.innerHTML = `
      <div style="font-family: sans-serif; padding: 20px; border: 2px solid #333; border-radius: 10px;">
        <h1 style="text-align: center; font-size: 28px; text-transform: uppercase; margin-bottom: 10px;">${signal.name}</h1>
        <div style="text-align: center; margin-bottom: 20px;">
            <span style="background: #eee; padding: 5px 10px; border-radius: 4px; font-size: 12px;">${signal.category} Signal</span>
        </div>
        
        <div style="margin: 20px 0; text-align: center;">
             <img src="${signal.image}" style="max-width: 250px; display: block; margin: 0 auto;" />
        </div>

        <div style="background: #f9f9f9; padding: 15px; border-radius: 5px; margin-bottom: 20px;">
            <h3 style="margin-top: 0;">Instruction:</h3>
            <p>${signal.explanation}</p>
            <p>${signal.detailedExplanation}</p>
        </div>
        
        <div style="margin-bottom: 20px;">
             <strong>Safety Notes:</strong>
              <ul>
                ${signal.safetyNotes.map(n => `<li>${n}</li>`).join('')}
              </ul>
        </div>
        
         <div style="text-align: center; margin-top: 30px; font-size: 10px; color: #666;">
          CraneSignal Pro Reference Card
        </div>
      </div>
    `;
    
    const opt = {
      margin: 0.5,
      filename: `${signal.name.toLowerCase().replace(/\s+/g, '-')}-card.pdf`,
      image: { type: 'png' as const, quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
    };

    html2pdf().set(opt).from(element).save();
  }


  return (
    <Layout>
      <div className="container px-4 md:px-6 py-12">
        <div className="max-w-3xl mx-auto text-center mb-12">
          <h1 className="text-4xl font-bold font-oswald mb-4">Download Course Materials</h1>
          <p className="text-muted-foreground text-lg">
            Get the full course handbook and individual signal reference cards for offline use and jobsite safety meetings.
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto">
          {/* Full Handbook */}
          <Card className="border-2 border-primary/20 bg-primary/5">
            <CardHeader>
              <CardTitle className="font-oswald text-2xl flex items-center gap-2">
                <ShieldCheck className="h-6 w-6 text-primary" />
                Complete Handbook
              </CardTitle>
              <CardDescription>
                All {signals.length} signals, safety guidelines, and quizzes in one document.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2 mb-6 text-sm text-muted-foreground">
                <li className="flex items-center gap-2"><CheckCircleIcon className="h-4 w-4" /> Printable A4 Format</li>
                <li className="flex items-center gap-2"><CheckCircleIcon className="h-4 w-4" /> High-resolution diagrams</li>
                <li className="flex items-center gap-2"><CheckCircleIcon className="h-4 w-4" /> Includes safety checklist</li>
              </ul>
              <Button 
                className="w-full font-oswald uppercase" 
                size="lg"
                onClick={handleDownloadFullCourse}
              >
                <Download className="mr-2 h-4 w-4" /> Download Full Course PDF
              </Button>
            </CardContent>
          </Card>

          {/* Individual Cards */}
          <Card>
            <CardHeader>
              <CardTitle className="font-oswald text-2xl flex items-center gap-2">
                <FileText className="h-6 w-6 text-muted-foreground" />
                Signal Reference Cards
              </CardTitle>
              <CardDescription>
                Individual cards for each signal. Great for daily toolbox talks.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4 max-h-[400px] overflow-y-auto pr-2">
                {signals.map(s => (
                  <div key={s.id} className="flex items-center justify-between p-2 rounded bg-muted/50">
                    <span className="font-medium text-sm">{s.name} Card</span>
                    <Button 
                        variant="ghost" 
                        size="sm" 
                        className="h-8"
                        onClick={() => handleDownloadSignal(s.id)}
                    >
                      <Download className="h-4 w-4" />
                    </Button>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </Layout>
  );
}

function CheckCircleIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
  );
}
